### ISSUE TITLE
Compatibility with typo3/cms-composer-installers >= v4

### ISSUE THREAD

**Issue by BobMali** [a-r-m-i-n/pw_comments#11]
Since the typo3/cms-composer-installers requires all public files to be inside the public resources directory, some minor adjustments are necessary to ensure compatibility. This is a prelude to TYPO3 v12 compatibility since typo3/cms-composer-installers v5 is required for it.

MR has been created #10

**Comment by BobMali** [comment]
Is there anyone maintaing this repository?

**Comment by a-r-m-i-n** [comment]
I used to maintain this extension, but I'm thinking about not to support it anymore (because of too much other extensions I'm already supporting). So, if you would like to take it, get it in touch with me, in TYPO3 Slack please.

**Comment by BobMali** [comment]
That sounds great! I will contact you.
