### ISSUE TITLE
Reply is not sorted the right way

### ISSUE THREAD

**Issue by Hogego** [a-r-m-i-n/pw_comments#6]
Hi, making a reply to an existing comment it is sorted the same way as a new comment. How can I change this?
Thanks a lot

**Comment by Hogego** [comment]
ah, sorry what I mean is that the entries are all listed the same way
I thought that the replies have to be place nearby under the comments with some space on the left ?

**Comment by Hogego** [comment]
for the moment they are listed as normal comments in the timeline

**Comment by a-r-m-i-n** [comment]
Do you have an example environment to look? Which TYPO3 and pw_comments version are you using?
